name = "TestPkg"
uuid = "619ccd1d-93bb-4860-9a87-f9c63370087c"
authors = ["Shisato Yano <shisatoyano@gmail.com> "]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
